# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'commit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	inhibit_all_warnings!

  # Pods for commit
  pod 'GoogleSignIn', '5.0.0'
  pod 'RealmSwift', '10.7.3'

end
